---


# tasks file for fourthTask


  - name: install zabbix for agents
    yum: 
       name: 
         - zabbix
         - zabbix-agent
       enablerepo: zabbix
       state: present



  - name: edit parameters
    ansible.builtin.lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      regexp: {{item.key}}
      line: {{item.value}}
      state: present
    with_items: '{{agent}}'

  - name: start zabbix
    systemd:
     name: zabbix-agent
     enabled: yes
     state: started

